name: Deploy FastAPI App to EC2

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  deploy:
    runs-on: self-hosted  # This runs on your EC2 self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🛠 Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI app
        run: |
          # Kill any running instance of uvicorn (optional safety)
          pkill -f uvicorn || true

          # Start app in background (for demo, not for production)
          nohup venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
